{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-admin.fullname" . }}
  labels:
    {{- include "azure-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  keycloak-client-secret: {{ .Values.secrets.keycloakClientSecret | quote }}
{{- end }}
