// <auto-generated />
using System;
using AzureAdmin.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AzureAdmin.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512121457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzureAdmin.API.Models.RegisteredRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureDevOpsOrganization")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AzureDevOpsProject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RepositoryIdOrName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("AzureDevOpsOrganization", "AzureDevOpsProject", "RepositoryIdOrName")
                        .IsUnique();

                    b.ToTable("RegisteredRepositories");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SprintLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.ReleasePullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AzureDevOpsPullRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegisteredRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceRefName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TargetRefName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredRepositoryId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ReleaseId", "RegisteredRepositoryId", "Phase")
                        .IsUnique();

                    b.ToTable("ReleasePullRequests");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.ReleaseTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("ReleaseId", "TeamId")
                        .IsUnique();

                    b.ToTable("ReleaseTeams");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentTeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.RegisteredRepository", b =>
                {
                    b.HasOne("AzureAdmin.API.Models.Team", "Team")
                        .WithMany("RegisteredRepositories")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.ReleasePullRequest", b =>
                {
                    b.HasOne("AzureAdmin.API.Models.RegisteredRepository", "RegisteredRepository")
                        .WithMany("ReleasePullRequests")
                        .HasForeignKey("RegisteredRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureAdmin.API.Models.Release", "Release")
                        .WithMany("PullRequests")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureAdmin.API.Models.Team", "Team")
                        .WithMany("ReleasePullRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegisteredRepository");

                    b.Navigation("Release");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.ReleaseTeam", b =>
                {
                    b.HasOne("AzureAdmin.API.Models.Release", "Release")
                        .WithMany("Teams")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureAdmin.API.Models.Team", "Team")
                        .WithMany("ReleaseTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.Team", b =>
                {
                    b.HasOne("AzureAdmin.API.Models.Team", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.RegisteredRepository", b =>
                {
                    b.Navigation("ReleasePullRequests");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.Release", b =>
                {
                    b.Navigation("PullRequests");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AzureAdmin.API.Models.Team", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RegisteredRepositories");

                    b.Navigation("ReleasePullRequests");

                    b.Navigation("ReleaseTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
